"""add donations table

Revision ID: 4ed4af6a72f4
Revises: 6e1e9ccc42fa
Create Date: 2026-01-17 21:53:06.387341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed4af6a72f4'
down_revision: Union[str, Sequence[str], None] = '6e1e9ccc42fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('payment_id', sa.String(), nullable=True))
    op.alter_column('donations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('donations', 'cause_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('donations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    op.alter_column('donations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('donations', 'cause_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('donations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('donations', 'payment_id')
    # ### end Alembic commands ###
